# Generated by Django 2.2 on 2019-04-25 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('logo', models.FileField(blank=True, null=True, upload_to='uploads/sponsors/')),
                ('external_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublishingState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('publish_state', models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Ready To Approve', 'Ready To Approve'), ('Published', 'Published')], max_length=20, null=True)),
                ('unpublishing_on', models.DateTimeField(blank=True, null=True)),
                ('do_not_publish_until', models.DateTimeField(blank=True, null=True, verbose_name='Do Not Publish Until')),
                ('not_for_external_use', models.BooleanField(default=False, verbose_name='Not For External Use')),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='content_manager.TemplateContent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='templatecontent',
            name='campaign',
            field=models.ManyToManyField(blank=True, related_name='campaign_related', to='content_manager.Campaign'),
        ),
        migrations.AddField(
            model_name='templatecontent',
            name='sponsor',
            field=models.ForeignKey(blank=True, help_text='Sponsor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='content_manager.Sponsor'),
        ),
    ]
